branches:
  except:
  - "/^.*\\/.*+$/"
language: ruby
rvm:
- 2.4.2
install:
- bundle install --full-index --path vendor/bundle --jobs=3 --retry=3
before_install:
- export TZ=America/Los_Angeles
- openssl aes-256-cbc -K $encrypted_4db5a3dd3a6f_key -iv $encrypted_4db5a3dd3a6f_iv
  -in spec/ldap_config.yml.enc -out spec/ldap_config.yml -d
script:
- bundle exec rspec
cache:
  directories:
  - vendor/bundle
notifications:
  slack: infinitered:vEwHyTPtHfTgpT5xdCA2ZkgX
